site_name: Solar Estimates
# Added site_url for better SEO and social sharing interoperability
site_url: https://rewiring-nz.github.io/solar-estimates/

theme:
  name: material
  features:
    - navigation.tabs          # Horizontal top bar links
    - navigation.tabs.sticky   # Keeps sub-navigation visible at the top
    - navigation.sections      # Groups sidebar items into clear sections
    - navigation.expand        # Automatically expands the active section
    - navigation.indexes       # Allows top-level titles to be clickable pages
    - toc.integrate            # TOC included in the left sidebar
    - content.code.copy

markdown_extensions:
  - toc:
      permalink: true          # Adds clickable anchors to headings
      toc_depth: 2             # How many heading levels to show in the sidebar
  - pymdownx.superfences:      # Enables mermaid diagrams
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  # --- Github Flavored Markdown Extensions ---
  - tables                     # Enables GFM-style tables
  - pymdownx.magiclink         # Makes URLs and emails clickable automatically
  - pymdownx.tasklist:         # Enables GFM-style checkboxes (- [ ] and - [x])
      custom_checkbox: true
  - pymdownx.tilde:            # Enables ~~strikethrough~~
      smart_delete: true
  - pymdownx.details           # Enables collapsible blocks
  - pymdownx.blocks.admonition # Enables GitHub-style [!TIP] blocks
  - admonition                 # Eables !!! blocks

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["src"] 

nav:
  - Home:
    - Home: index.md
    - About: about.md
    - License: license.md 
    - Contact: contact.md
  - Download: downloads.md
  - User Guide:
    - User Guide: user/index.md
    - Pipeline Quickstart: user/pipeline-quickstart.md
    - Pipeline - Source Data : user/how-to-use-your-own-data.md
    - QGIS Quickstart: user/qgis-quickstart.md
  - Developer Guide:
    - Developer Guide: developer/index.md
    - Key Concepts: developer/concepts.md
    - Design: developer/design.md
    - API Reference: developer/reference.md
    - Github Guide: developer/github-contribution-guide.md
    - Website Maintenance Guide: developer/website-guide.md
    - Source Code: https://github.com/rewiring-nz/solar-estimates
    - Kanban: https://github.com/orgs/rewiring-nz/projects/3
